services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  web:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    # environment:
    #   PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build: ./client
    environment:
      PORT: 3000
      # PROXY_API: http://phbeyondmd:8000/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

volumes:
  db:
    driver: local
